### ISSUE TITLE
PHP Warning:  file_get_contents  failed to open stream: HTTP request failed! HTTP/1.1 406 Not Acceptable

### ISSUE THREAD

**Issue by amjtn** [dipeshbaheti95/vcommission-coupon-portal#1]
Thank you for sharing the script. Great work

**Comment by dipeshbaheti95** [comment]
1. Make sure you have an api key provieded by vcommission.
2. Hit the api and test wether you are getting data on web browser or not.
3. I made it in php version 5.x so try changing php version on your server side configuration.

Hope it helps!!!
Good Luck :)

**Comment by amjindia** [comment]
Hi,

Thank you for the keen reply. API URL from Vcommission working fine on Web browser. Also, PHP version is 5.4. But still same issue occurs. Please help me to fix this issue.

Thanks

**Comment by amjindia** [comment]
Hi,

After a long research fixed the issue. Replace following lines

$browserua = $_SERVER['HTTP_USER_AGENT'];

$opts = array(
  'http'=>array(
    'method'=>"GET",
    'header'=>"Accept-language: en\r\n" .
              "Cookie: foo=bar\r\n" .
              "User-Agent: $browserua" 
  )
);

$context = stream_context_create($opts);
$jsondata = file_get_contents('https://tools.vcommission.com/api/coupons.php?apikey=1f40c66642ef1ce8d4b04010f810557a03299971394feebd501e401e7a9a460c', false, $context); // Dont forget to replace with your api address
$data = json_decode($jsondata, true);

Instead of

$jsondata = file_get_contents('http://tools.vcommission.com/api/coupons.php?apikey=1f40c66642ef1ce8d4b04010f810557a03299971394feebd501e401e7a9a460c'); // Dont forget to replace with your api address
$data=json_decode($jsondata, true);

Thanks
